---
- block:
    - name: Install batsignal
      become: true
      pacman:
        name:
          - batsignal

    - name: Enable batsignal service
      systemd:
        name: batsignal
        enabled: yes
        scope: user
