# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

plugins=(
    gitfast
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

# Aliases
alias ls="eza --icons always"

# cargo path
export PATH="$HOME/.cargo/env:$PATH"
# yarn path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# mason LSPs
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
# dotnet path
export PATH="$HOME/.dotnet:$PATH"

# needed for Neovim colors inside of tmux
export TERM="xterm-256color"

# zoxide
eval "$(zoxide init --cmd cd zsh)"

# oh-my-posh
eval "$(oh-my-posh init zsh --config /home/jan/.config/zsh-theme.omp.json)"
