---
- block:
    - name: Create cursor directory
      become: true
      file:
        path: /usr/share/icons/Catppuccin-Macchiato-Dark-Cursors 
        state: directory
    
    - name: Extract cursor theme
      become: true
      unarchive:
        src: https://github.com/catppuccin/cursors/releases/latest/download/Catppuccin-Macchiato-Dark-Cursors.zip
        dest: /usr/share/icons/Catppuccin-Macchiato-Dark-Cursors
        remote_src: yes
