---
- block:
    - name: Install additional packages
      become: true
      pacman:
        name:
          - firefox
          - chromium
          - libreoffice-still
          - okular
          - thunar
          - pinta
          - keepassxc
          - discord
          - htop
          - flameshot
          - optipng
          - openssh
          - gvfs-smb
          - borg
          - python-llfuse
          - texlive-core
          - nextcloud-client
