vim.api.nvim_set_var("vimtex_view_general_viewer", "okular")
vim.api.nvim_set_var("vimtex_context_pdf_viewer", "okular")
vim.api.nvim_set_var("vimtex_indent_enabled", 1)
vim.api.nvim_set_var("vimtex_syntax_enabled", 1)
vim.api.nvim_set_var("vimtex_mappings_prefix", "<space>")
