---
- name: Dev Setup
  hosts: localhost
  connection: local
  vars:
    is_desktop: "yes"
    external_drives: "no"
  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - additional
        - alacritty
        - directories
        - feh
        - fonts
        - git
        - i3
        - languages
        - mate-panel
        - modprobe
        - neovim
        - polybar
        - rofi
        - spotify
        - standard
        - tmux
        - virtualization
        - zsh
