---
- name: Dev Setup
  hosts: localhost
  connection: local
  vars:
    is_desktop: "no"
    external_drives: "no"
    multi_monitor: "no"
    mkinitcpio: "yes"
  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - directories
        - standard
        - sddm
        - network
        - i3
        - xrandr
        - git
        - picom
        - betterlockscreen
        - additional
        - zsh
        - alacritty
        - feh
        - fonts
        - languages
        - modprobe
        - neovim
        - polybar
        - rofi
        - tmux
        - virtualization
        - alsa
        - mariadb
        - gtk
        - android
        - cursor
        - alsa
