---
- name: Dev Setup
  hosts: localhost
  connection: local
  vars:
    is_desktop: "no"
    external_drives: "no"
    multi_monitor: "no"
  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - directories
        - standard
        - sddm
        - i3
        - git
        - picom
        - additional
        - zsh
        - alacritty
        - feh
        - fonts
        - languages
        - mate-panel
        - modprobe
        - neovim
        - polybar
        - rofi
        - spotify
        - tmux
        - virtualization
        - alsa
        - mariadb
        - gtk
