---
- name: Dev Setup
  hosts: localhost
  connection: local
  vars:
    is_laptop: false
    multi_monitor: false
    mkinitcpio: true
  tasks:
    - name: Default roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - directories
        - standard
        - sddm
        - network
        - i3
        - xrandr
        - git
        - picom
        - betterlockscreen
        - additional
        - zsh
        - alacritty
        - feh
        - fonts
        - languages
        - modprobe
        - neovim
        - polybar
        - rofi
        - tmux
        - alsa
        - mariadb
        - gtk
        - android
        - cursor
        - alsa

    - name: Desktop only roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - virtualization
      when: not is_laptop

    - name: Laptop only roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - power_management
        - fingerprint
        - screen
        - bluetooth
      when: is_laptop
