#!/bin/bash
set -e

if ! [ -x "$(command -v ansible)" ]; then
    sudo pacman -S ansible --noconfirm
fi

read -p "Is this a desktop machine for virtualization purposes (y/n)?" is_desktop
read -p "Are directories for external storage needed? (y/n)" external_storage_needed

if [ $is_desktop == "y" ] && [ $external_storage_needed == "y" ]; then
    ansible-playbook -K playbook.yml -e is_dektop="yes" -e external_drives="yes"
    exit 1
fi

if [ $is_desktop == "y" ]; then
    ansible-playbook -K playbook.yml -e is_dektop="yes"
    exit 1
fi

if [ $external_storage_needed == "y" ]; then
    ansible-playbook -K playbook.yml -e external_drives="yes"
    exit 1
fi

ansible-playbook -K playbook.yml
