---
- block:
    - name: Install needed packages
      become: true
      pacman:
        name:
          - bluez
          - bluez-utils
          - blueman

    - name: Enable bluetooth service
      systemd:
        name: bluetooth
        enabled: yes 
