---
- block:
    - name: Install SDDM and theme dependencies
      become: true
      pacman:
        name:
          - sddm
          - qt5-graphicaleffects
          - qt5-svg
          - qt5-quickcontrols2

    - name: Create theme directory
      become: true
      file:
        path: /usr/share/sddm/themes/catppuccin-macchiato
        state: directory
        recurse: true

    - name: Download and extract Catppuccin theme
      become: true
      unarchive:
        src: https://github.com/catppuccin/sddm/releases/latest/download/catppuccin-macchiato.zip
        dest: /usr/share/sddm/themes/catppuccin-macchiato
        remote_src: yes

    - name: Copy sddm configuration file
      become: true
      copy:
        src: ../files/sddm.conf
        dest: /etc/sddm.conf

    - name: Enable SDDM in systemd
      become: true
      systemd:
        name: sddm
        enabled: yes

    - name: Remove cloned theme repo
      file:
        path: /tmp/sddm-theme
        state: absent
