---
- block:
    - name: Install SDDM
      become: true
      pacman:
        name: sddm

    - name: Enable SDDM in systemd
      become: true
      systemd:
        name: sddm
        enabled: yes
