---
- blocks:
    - name: Install zsh
      become: true
      pacman:
        name: zsh

    - name: Change default shell to zsh
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Install Powerlevel10k
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    - name: Install zsh-history-substring-search
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search.git
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
