---
- block:
    - name: Download Catppuccin theme
      get_url:
        url: https://github.com/catppuccin/gtk/releases/latest/download/Catppuccin-Macchiato-Standard-Sapphire-Dark.zip
        dest: ~/Downloads/Catppuccin-Macchiato.zip

    - name: Create theme directory
      become: true
      file:
        path: /usr/share/themes/Catppuccin-Macchiato-Standard-Sapphire-Dark
        state: directory
        recurse: true

    - name: Unzip theme
      become: true
      unarchive:
        src: ~/Downloads/Catppuccin-Macchiato.zip
        dest: /usr/share/themes/Catppuccin-Macchiato-Standard-Sapphire-Dark

    - name: Create GTK-3.0 directory
      file:
        path: ~/.config/gtk-3.0
        state: directory

    - name: Copy GTK-3.0 settings
      copy:
        src: ../files/settings.ini
        dest: ~/.config/gtk-3.0/settings.ini
