---
- block:
    - name: Install MariaDB
      become: true
      pacman:
        name:
          - mariadb

    - name: Enable MariaDB service
      become: true
      systemd:
        name: mariadb
        enabled: yes
