---
- block:
    - name: Install Spotify
      become: true
      shell: yay -S spotify --noconfirm

    - name: Download Spicetify
      shell: curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh

    - name: Create Spicetify directory
      file:
        path: ~/.config/spicetify/Themes
        recurse: true

    - name: Download Spicetify Themes
      git:
        repo: https://github.com/spicetify/spicetify-themes.git
        dest: ~/.config/spicetify/spicetify-themes

    - name: Move themes to configuration directory
      shell: cp -r * ~/.config/spicetify/spicetify-themes ~/.config/spicetify/Themes

    - name: Remove theme repository
      shell: rm -rf ~/.config/spicetify/spicetify-themes

    - name: Apply default theme
      shell: spicetify config current_theme default
