---
- block:
    - name: Create i3 directory
      file:
        path: ~/.config/i3
        state: directory

    - name: Install i3 packages
      become: true
      pacman:
        name:
          - i3-gaps
          - i3blocks

    - name: Set x11-keymap
      become: true
      shell: localectl set-x11-keymap de
      ignore_errors: true

    - name: Copy multiple monitors i3 configuration file
      copy:
        src: ../files/multi_monitor_config
        dest: ~/.config/i3/config
      when: multi_monitor and not is_laptop

    - name: Copy default i3 configuration file
      copy:
        src: ../files/config
        dest: ~/.config/i3/config
      when: not multi_monitor and not is_laptop

    - name: Copy laptop i3 configuration file
      copy:
        src: ../files/laptop_config
        dest: ~/.config/i3/config
      when: is_laptop
