---
- block:
    - name: Create i3 directory
      file:
        path: ~/.config/i3
        state: directory

    - name: Install i3 packages
      become: true
      pacman:
        name:
          - i3-gaps
          - i3blocks
          - i3lock

    - name: Set x11-keymap
      become: true
      shell: localectl set-x11-keymap de

    - name: Copy monitor script
      copy:
        src: ../files/set_monitors.sh
        dest: ~/.config/i3/set_monitors.sh
        mode: +x
      when: multi_monitor == "yes"

    - name: Copy multiple monitors i3 configuration file
      copy:
        src: ../files/multi_monitor_config
        dest: ~/.config/i3/config
      when: multi_monitor == "yes"

    - name: Copy default i3 configuration file
      copy:
        src: ../files/config
        dest: ~/.config/i3/config
      when: multi_monitor != "yes"
