---
- block:
    - name: Install audio packages
      become: true
      pacman:
        name:
          - alsa-utils
          - pipewire-audio
          - pipewire-pulse
          - pipewire-alsa
          - qemu-audio-alsa
          - pavucontrol
          - wireplumber

    - name: Enable sockets PipeWire
      systemd:
        name: pipewire.socket
        enabled: yes
        scope: user

    - name: Enable sockets for PipeWire-Pulse
      systemd:
        name: pipewire-pulse.socket
        enabled: yes
        scope: user

    - name: Enable Wireplumber
      systemd:
        name: wireplumber.service
        enabled: yes
        scope: user
