---
- block:
    - name: Create Polybar configuration directory
      file:
        path: ~/.config/polybar
        state: directory

    - name: Install Polybar
      become: true
      pacman:
        name: polybar

    - name: Copy start script
      copy:
        src: ../files/start_polybar.sh
        dest: ~/.config/polybar/start_polybar.sh
        mode: +x

    - name: Copy configuration file
      copy:
        src: ../files/config.ini
        dest: ~/.config/polybar/config.ini
