---
- block:
    - name: Create Polybar configuration directory
      file:
        path: ~/.config/polybar
        state: directory

    - name: Install Polybar
      become: true
      pacman:
        name: polybar

    - name: Copy start script for single monitor
      copy:
        src: ../files/start_polybar.sh
        dest: ~/.config/polybar/start_polybar.sh
        mode: +x
      when: multi_monitor == "no"

    - name: Copy start script for two monitors
      copy:
        src: ../files/start_polybar_multi_monitor.sh
        dest: ~/.config/polybar/start_polybar.sh
        mode: +x
      when: multi_monitor == "yes"

    - name: Copy configuration file for single monitor
      copy:
        src: ../files/config.ini
        dest: ~/.config/polybar/config.ini

    - name: Copy configuration file for two monitors
      copy:
        src: ../files/config_multi_monitor.ini
        dest: ~/.config/polybar/config.ini
