---
- block:
    - name: Clone i3lock-color
      git:
        repo: https://github.com/Raymo111/i3lock-color
        dest: /tmp/i3lock-color

    - name: Install i3lock-color dependency
      become: true
      script:
        cmd: /tmp/i3lock-color/install-i3lock-color.sh

    - name: Install ImageMagick dependency
      become: true
      pacman:
        name: imagemagick

    - name: Install Xorg dependencies
      become: true
      pacman:
        name:
          - xorg-xdpyinfo
          - xorg-xrdb
          - xorg-xset

    - name: Extract betterlockscreen executable
      unarchive:
        src: https://github.com/betterlockscreen/betterlockscreen/archive/refs/heads/main.zip
        dest: /tmp
        remote_src: yes

    - name: Copy betterlockscreen executable to bin
      become: true
      copy:
        src: /tmp/betterlockscreen-main/betterlockscreen
        dest: /usr/local/bin/betterlockscreen
        owner: "{{ ansible_user_id }}"
        mode: "u+x"

    - name: Copy betterlockscreen systemd service
      become: true
      copy:
        src: /tmp/betterlockscreen-main/system/betterlockscreen@.service
        dest: /usr/lib/systemd/system/betterlockscreen@.service

    - name: Enable betterlockscreen service
      systemd:
        name: betterlockscreen
        enable: true
        state: started
        scope: user

    - name: Remove betterlockscreen directory
      file:
        state: absent
        path: /tmp/betterlockscreen-main

    - name: Remove zip file
      file:
        state: absent
        path: /tmp/main.zip

