---
- block:
  - name: Install packages
    become: true
    pacman:
      name:
        - virt-manager
        - qemu
        - libvirt
        - ovmf
        - bridge-utils
        - swtpm
        - dnsmasq
        - barrier
    when: is_desktop == "yes"

  - name: Enable libvirt service
    become: true
    systemd:
      name: libvirtd
      enabled: yes

  - name: Create libvirt group
    become: true
    name: libvirt
    state: present

  - name: Add user to libvirt group
    become: true
    user:
      name: {{ user }} 
      group: libvirt
      append: yes

  - name: Copy libvirtd configuration file
    become: true
    copy:
      src: ../files/libvirtd.conf
      dest: /etc/libvirt/libvirtd.conf

  - name: Restart libvirtd service
    become: true
    systemd:
      name: libvirtd
      state: restarted
      daemon_reload: yes
