---
- block:
  - name: Install packages
    become: true
    pacman:
      name:
        - virt-manager
        - qemu
        - libvirt
        - ovmf
        - bridge-utils
        - swtpm
        - barrier
    when: is_desktop == "yes"

  - name: Enable libvirt service
    become: true
    systemd:
      name: libvirtd
      enabled: yes

