---
- block:
  - name: Install packages
    become: true
    pacman:
      name:
        - virt-manager
        - qemu
        - libvirt
        - ovmf
        - bridge-utils
        - swtpm
        - dnsmasq
        - barrier
        - qemu-audio-pa
    when: is_desktop == "yes"

  - name: Enable libvirt service
    become: true
    systemd:
      name: libvirtd
      enabled: yes
    when: is_desktop == "yes"

  - name: Create libvirt group
    become: true
    group:
      name: libvirt
      state: present
    when: is_desktop == "yes"

  - name: Add user to libvirt group
    become: true
    user:
      name: "{{ ansible_user_id }}" 
      groups: libvirt
      append: yes
    when: is_desktop == "yes"

  - name: Copy libvirtd configuration file
    become: true
    copy:
      src: ../files/libvirtd.conf
      dest: /etc/libvirt/libvirtd.conf
    when: is_desktop == "yes"

  - name: Restart libvirtd service
    become: true
    systemd:
      name: libvirtd
      state: restarted
      daemon_reload: yes
    when: is_desktop == "yes"
