---
- block:
    - name: Install languages and framework
      become: true
      pacman:
        name:
          - dotnet-sdk
          - mono-msbuild
          - python
          - python-pip
          - python-virtualenv
          - rust
          - jdk-openjdk
          - nodejs
