---
- block:
    - name: Install languages and framework
      become: true
      pacman:
        name:
          - dotnet-sdk
          - mono-msbuild
          - rust
          - jdk-openjdk
          - nodejs
          - npm

    - name: Install Python and correpsonding packages
      become: true
      pacman:
        name:
          - python
          - python-pip
          - python-virtualenv
          - jupyterlab
          - jupyter-notebook
