---
- block:
    - name: Install languages and frameworks
      become: true
      pacman:
        name:
          - dotnet-sdk
          - mono-msbuild
          - rust
          - jdk-openjdk
          - nodejs
          - npm

    # === Python installation === #
    - name: Install Python and correpsonding packages
      become: true
      pacman:
        name:
          - python
          - python-pip
          - python-virtualenv
          - jupyterlab
          - jupyter-notebook

    # === Rust installation === #
    - name: Check if cargo is installed
      shell: command -v cargo
      register: cargo_is_installed
      ignore_errors: yes

    - name: Download rustup installer
      when: cargo_is_installed is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'

    - name: Install Rust
      when: cargo_is_installed is failed
      shell: /tmp/sh.rustup.rs -y

