---
- block:
    - name: Install languages and frameworks
      become: true
      pacman:
        name:
          - jdk-openjdk
          - nodejs
          - npm

    # === Python installation === #
    - name: Install Python and correpsonding packages
      become: true
      pacman:
        name:
          - python
          - python-pip
          - python-virtualenv
          - jupyterlab
          - jupyter-notebook

    # === Rust installation === #
    - name: Check if cargo is installed
      shell: command -v cargo
      register: cargo_is_installed
      ignore_errors: yes

    - name: Download rustup installer
      when: cargo_is_installed is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'

    - name: Install Rust
      when: cargo_is_installed is failed
      shell: /tmp/sh.rustup.rs -y

    # === .NET isntallation === #
    - name: Install base .NET packages
      become: true
      pacman:
        name:
          - dotnet-sdk
          - mono-msbuild

    - name: Create netcoredbg directory
      become: true
      file:
        path: /usr/local/bin/netcoredbg
        state: directory

    - name: Extract netcoredbg
      become: true
      unarchive:
        src: https://github.com/Samsung/netcoredbg/releases/latest/download/netcoredbg-linux-amd64.tar.gz
        dest: /usr/local/bin/netcoredbg
        remote_src: yes

    - name: Set permission for netcoredbg
      become: true
      shell: chmod 744 /usr/local/bin/netcoredbg/*
        



