---
- block:
    - name: Install Neovim packages
      become: true
      pacman:
        name:
          - neovim
          - gdb

    - name: Create Neovim directory
      file:
        path: ~/.config/nvim
        state: directory

    - name: Copy init files
      copy:
        src: ../files/
        dest: ~/.config/nvim/

    - name: Create Packer directories
      file:
        path: ~/.local/share/nvim/site/pack/packer/start
        state: directory
        recurse: true

    - name: Download packer.nvim
      git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        depth: 1

    - name: Install plugins
      shell: nvim +PackerInstall +qa



