---
- block:
    - name: Install Neovim package
      become: true
      pacman:
        name: neovim

    - name: Create Neovim directory
      file:
        path: ~/.config/nvim
        state: directory

    - name: Copy init files
      copy:
        src: ../files/
        dest: ~/.config/nvim/

    - name: Create Packer directories
      file:
        path: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        state: directory
        recurse: true

    - name: Download packer.nvim
      get_url:
        url: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

    - name: Install plugins
      shell: nvim +PackerInstall +qa



