---
- block:
    - name: Creater user fonts directory
      file:
        path: ~/.local/share/fonts
        state: directory
        recurse: true

    - name: Install Font Awesome
      become: true
      pacman:
        name: ttf-font-awesome

    - name: Create Meslo LGS Nerd Font directory
      file:
        path: ~/.local/share/fonts/ttf/MesloLGS NF
        state: directory
        recurse: true

    - name: Download Meslo LGS Nerd Font
      get_url:
        url: "{{ item.url }}"
        dest: "~/.local/share/fonts/ttf/MesloLGS NF/{{ item.name }}"
      with_items:
        - {
            url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf,
            name: 'MesloLGS NF Regular.ttf'
          }
        - {
            url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf,
            name: 'MesloLGS NF Bold.ttf'
          }
        - {
            url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf,
            name: 'MesloLGS NF Italic.ttf'
          }
        - {
            url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf,
            name: 'MesloLGS NF Bold Italic.ttf'
          }

    - name: Install powerline-fonts
      become: true
      pacman:
        name: powerline-fonts

    - name: Download Iosevka Nerd Font
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.zip
        dest: ~/.local/share/fonts/
        remote_src: yes

    - name: Reload font cache
      shell: fc-cache
